server:
  port: 80

  #db
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chat?serverTimezone=GMT%2B8
    password: root
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    InitialSize: 5
    maxWait: 60000
    maxActive: 10
    filters: stat
  redis:
    port: 6379
    host: 127.0.0.1

  security:
    user:
      name: fate
      password: 123456
      roles: [admin,guest]

#开启驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true

